services:
  # Backend API service
  - type: web
    name: entertainment-reviews-api
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install && ./scripts/run-with-env.sh npm run build
    startCommand: cd backend && ./scripts/run-with-env.sh npm run migrate:safe && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: entertainmentdb
          property: connectionString
      - key: CRON_SECRET
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: EMAIL_SERVICE
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: RAWG_API_KEY
        sync: false
      - key: RECAPTCHA_SECRET_KEY
        sync: false
      - key: ZOHO_APP_PASSWORD
        sync: false

  # Frontend service
  - type: web
    name: entertainmentME
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: entertainmentdb
    databaseName: entertainmentdb
    user: entertainmentdb_user
    plan: free 