services:
  # Backend API service
  - type: web
    name: entertainment-reviews-api
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: entertainmentdb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

  # Frontend service
  - type: web
    name: entertainmentME
    env: node
    region: oregon
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npx serve -s build
    envVars:
      - key: REACT_APP_API_URL
        value: https://entertainment-reviews-api.onrender.com

databases:
  - name: entertainmentdb
    databaseName: entertainmentdb
    user: entertainmentdb_user
    plan: free 