-- Complete User model with all fields
ALTER TABLE "User" 
ADD COLUMN IF NOT EXISTS "display_name" TEXT,
ADD COLUMN IF NOT EXISTS "avatar_url" TEXT,
ADD COLUMN IF NOT EXISTS "bio" TEXT,
ADD COLUMN IF NOT EXISTS "location" TEXT,
ADD COLUMN IF NOT EXISTS "website" TEXT,
ADD COLUMN IF NOT EXISTS "last_login" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS "last_activity" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS "is_active" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS "login_count" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN IF NOT EXISTS "preferences" JSONB NOT NULL DEFAULT '{}',
ADD COLUMN IF NOT EXISTS "content_filters" JSONB NOT NULL DEFAULT '{}',
ADD COLUMN IF NOT EXISTS "email_verified" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "verification_token" TEXT,
ADD COLUMN IF NOT EXISTS "verification_token_expires" TIMESTAMP;
